### ISSUE TITLE
Error when importing library on 1.2.0

### ISSUE THREAD

**Issue by guiscaranse** [amplitude/experiment-python-server#34]
## Expected Behavior
Import library successfully.

## Current Behavior
```
Traceback (most recent call last):
  File "main.py", line 1, in <module>
    import amplitude_experiment
  File "/home/runner/NoteworthyFortunateParallelalgorithm/venv/lib/python3.10/site-packages/amplitude_experiment/__init__.py", line 11, in <module>
    from .factory import Experiment
  File "/home/runner/NoteworthyFortunateParallelalgorithm/venv/lib/python3.10/site-packages/amplitude_experiment/factory.py", line 3, in <module>
    from .local.client import LocalEvaluationClient
  File "/home/runner/NoteworthyFortunateParallelalgorithm/venv/lib/python3.10/site-packages/amplitude_experiment/local/client.py", line 8, in <module>
    from .config import LocalEvaluationConfig
  File "/home/runner/NoteworthyFortunateParallelalgorithm/venv/lib/python3.10/site-packages/amplitude_experiment/local/config.py", line 1, in <module>
    from src.amplitude_experiment.assignment.assignment_config import AssignmentConfig
ModuleNotFoundError: No module named 'src'
```

## Steps to Reproduce
1. Install 1.2.0
2. Try to import library
3. Error

## Environment
- SDK Version: 1.2.0
- Language Version: Tested on 3.10 and 3.11

**Comment by tyiuhc** [comment]
Hi @guiscaranse, thank you so much for raising this issue! This has been fixed in v1.2.1
